proxies:
proxy-providers:
  PP_Bebas:
    type: file
    path: "./config/proxy_provider/bebas.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 50
  PP_Indonesia:
    type: file
    path: "./config/proxy_provider/indonesia.yaml"
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 100
proxy-groups:
  - name: Best Ping
    type: url-test
    disable-udp: false
    url: http://cp.cloudflare.com/generate_204
    interval: 200
    use:
      - PP_Bebas
  - name: Pilihan
    type: select
    disable-udp: false
    url: http://cp.cloudflare.com/generate_204
    interval: 200
    use:
      - PP_Bebas
  - name: ğŸ‡®ğŸ‡©Indonesia
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    interval: 200
    disable-udp: false
    use:
      - PP_Indonesia
  - name: ğŸŒDirect
    type: select
    proxies:
      - DIRECT
  - name: â›”ï¸Reject
    type: select
    proxies:
      - REJECT
  - name: ğŸŒBebas
    type: select
    disable-udp: false
    url: http://cp.cloudflare.com/generate_204
    interval: 200
    proxies:
      - Best Ping
      - Pilihan
  - name: ğŸ§³Mode Indonesia
    type: select
    url: http://cp.cloudflare.com/generate_204
    interval: 200
    disable-udp: false
    proxies:
      - ğŸ‡®ğŸ‡©Indonesia
      - ğŸŒBebas
      - ğŸŒDirect
rule-providers:
### classical / ipcidr / domain
  RP_Direct:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-direct.yaml"
  RP_Reject:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-reject.yaml"
  RP_WhatsApp:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-whatsapp.yaml"
  RP_Line:
    type: file
    behavior: domain
    path: "./config/rule_provider/rule-line.yaml"
  RP_Lan_Domain:
    type: file
    behavior: domain
    path: "./config/rule_provider/rule-lan-domain.yaml"
  RP_Lan_IP:
    type: file
    behavior: ipcidr
    path: "./config/rule_provider/rule-lan-ip.yaml"
  RP_DNS:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-dns.yaml"
  RP_Video:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-video.yaml"
  RP_Musik:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-musik.yaml"
  RP_Domain_Indo:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-domain-indo.yaml"
  RP_Akaimahd:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-akaimahd.yaml"
  RP_Disney_Joox:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-disney-joox.yaml"
  RP_Market_Place:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-market-place.yaml"
  RP_Ewallet:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-ewallet.yaml"
rules:
  - DOMAIN,clash.razord.top,ğŸŒDirect
  - DOMAIN,yacd.haishan.me,ğŸŒDirect
  - IP-CIDR,192.18.0.1/16,â›”ï¸Reject,no-resolve
### Anti gagal Block Ads
  - DOMAIN-SUFFIX,googlesyndication.com,ğŸŒBebas
  - DOMAIN-SUFFIX,googleadservices.com,â›”ï¸Reject
  - GEOSITE,CATEGORY-ADS-ALL,â›”ï¸Reject
  - GEOSITE,win-spy,â›”ï¸Reject
  - GEOSITE,google-ads,â›”ï¸Reject
### Paket Akrab
  - RULE-SET,RP_WhatsApp,ğŸŒDirect
  - GEOSITE,whatsapp,ğŸŒDirect
  - RULE-SET,RP_Line,ğŸŒDirect
  - PROCESS-NAME,com.whatsapp,ğŸŒDirect
  - PROCESS-NAME,com.whatsapp.w4b,ğŸŒDirect
  - PROCESS-NAME,com.yowhatsapp,ğŸŒDirect
  - PROCESS-NAME,com.fmwhatsapp,ğŸŒDirect
  - PROCESS-NAME,com.gbwhatsapp,ğŸŒDirect
### Fix lemot youtube
  - AND,((GEOSITE, YOUTUBE),(NETWORK, UDP)),â›”ï¸Reject
### Domain Indo khusus VPN INDO
  - AND,((DST-PORT,5228-5230),(NETWORK,TCP),(DOMAIN,mtalk.google.com)),ğŸ§³Mode Indonesia
  - RULE-SET,RP_Video,ğŸ§³Mode Indonesia
  - RULE-SET,RP_Musik,ğŸ§³Mode Indonesia
  - RULE-SET,RP_Disney_Joox,ğŸ§³Mode Indonesia
  - RULE-SET,RP_Akaimahd,ğŸ§³Mode Indonesia
  - RULE-SET,RP_Market_Place,ğŸ§³Mode Indonesia
  - RULE-SET,RP_Ewallet,ğŸ§³Mode Indonesia
  - RULE-SET,RP_Domain_Indo,ğŸ§³Mode Indonesia
### Umum
  - RULE-SET,RP_DNS,ğŸŒBebas
  - RULE-SET,RP_Direct,ğŸŒDirect
  - RULE-SET,RP_Lan_Domain,ğŸŒDirect
  - GEOIP,private,ğŸŒDirect,no-resolve
  - RULE-SET,RP_Lan_IP,ğŸŒDirect,no-resolve
### REJECT
  - RULE-SET,RP_Reject,â›”ï¸Reject
### Yang tidak di rule otomatis kesini
  - GEOIP,ID,ğŸ§³Mode Indonesia
  - MATCH,ğŸŒBebas
  - MATCH,GLOBAL
